spring:
  application:
    name: spring-gateway-oauth2-keycloak-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master
server:
  port : 9021
#Actuator health check    
management:
  endpoints:
    web:
      exposure:
        include: "*"